version: '3'
services:
  redis-server:
    container_name: server_redis
    image: 'redis'
    ports:
      - "6379:6379"
  java-service:
    container_name: app_redis
    build: .
    links:
      - redis-server
    ports:
      - "8080:8080"