server:
  port: 8080

spring:
  redis:
    host: redis-server
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0

logging:
  level:
    org:
      springframework:
        web: DEBUG